thrift/sampling.thrift
This is a breaking change, I might have to keep 4 as is and add 5 on SamplingStrategyResponse if someone has already deployed a client with the old change.
=> Update operation sampling strategy

thrift/sampling.thrift
Sooooo, the generated python code doesn't like the ordering.
=> Change thrift ordering

thrift/baggage.thrift
Reverts uber/jaeger-idl#29
1) thrift language support for maps is weird, prefer wire format to be as simple as possible. 
2) the list is more efficient than map
3) struct is more easy to extend if we wanted to return more fields in baggage restrictions, with map it's a breaking change
=> Revert "Use map instead of list for baggage restrictions"

thrift/zipkincore.thrift
Fixes https://github.com/uber/jaeger/issues/335
=> Zipkin thrift add ipv6 and traceIdHigh to support 128 trace ids

thrift/agent.thrift, thrift/aggregation_validator.thrift, thrift/baggage.thrift, thrift/crossdock/tracetest.thrift, thrift/dependency.thrift, thrift/jaeger.thrift, thrift/sampling.thrift, thrift/zipkincore.thrift
Added namespaces for netcore (C# with .netcore). Namespaces are:
1. ```Jaeger.Thrift```
2. ```Jaeger.Thrift.Agent```
3. ```Jaeger.Thrift.Agent.Zipkin```
I did not modify the build script because at the moment I'm using an [unofficial version of thrift that supports netcore](https://github.com/apache/thrift/pull/1379)
=> Added netcore namespace

Makefile, thrift/agent.thrift, thrift/aggregation_validator.thrift, thrift/baggage.thrift, thrift/crossdock/tracetest.thrift, thrift/dependency.thrift, thrift/jaeger.thrift, thrift/sampling.thrift, thrift/zipkincore.thrift
For now we can set only global php namespace in generator:
thrift -r --gen php:psr4,nsglobal=Jaeger\\ThriftGen ./
This is not very usable because some classes from jaeger.thrift missing as they has same name as zipkincore.thrift (e.g. Span)
Simple solution is to specify namespace for particular type.
=> PHP namespace.

thrift/jaeger.thrift
This reverts PR #50 that added `incomplete` flag.
I checked all Jaeger clients, none of them import IDL with that flag. The respective PR in the main repo (https://github.com/jaegertracing/jaeger/pull/979) is still WIP and requires some evidence of client work done to demonstrate the new functionality, therefore the IDL change was premature.
=> Revert "Incomplete span support (#50)"

proto/zipkin.proto
Signed-off-by: Abhilash Gnan <abhilashgnan@gmail.com>
- Adding `zipkin.proto` file to support sending Zipkin Protobuf spans to jaeger-collector
- Parent issue: https://github.com/jaegertracing/jaeger/pull/1695
=> Add zipkin.proto

thrift/zipkincore.thrift
Signed-off-by: Marc Bramaud <m.duboucheron@gmail.com>
- typo in `thrift/zipkincore.thrift` docs.
I was pointed to this repo in jaegertracing/jaeger-client-go#475, hope this is the right source file :)
=> chore(docs): fixed typos in thrift/zipkincore.thrift

thrift/jaeger.thrift
- https://github.com/jaegertracing/jaeger/issues/2005
- Extend Batch to allow sending batch sequence number and some data loss stats
=> Add ability to send data loss stats in Batch

Makefile
- Thrift containers are not removed after running. This leaves a lot of clutter.
- Remove flag for ended thrift containers was missing
=> Delete Thrift container after run

Makefile
- https://github.com/jaegertracing/jaeger/issues/1972
- https://github.com/uber/tchannel-go/issues/781
- https://github.com/jaegertracing/jaeger-client-csharp/issues/139
- https://github.com/jaegertracing/jaeger-idl/issues/62
- https://github.com/jaegertracing/jaeger-idl/pull/63
- https://github.com/jaegertracing/docker-protobuf/pull/15
- The Go and C# clients need to upgrade Thrift to `0.13`. Go because of a inherited Prometheus dependency, C# because of strong naming assemblies. The current `jaeger-idl` only produces `0.9.2`. Right now, we have to manually adjust the `Makefile` to use the necessary version. There is no way to also use this as submodule.
I would like to check if other libraries need to stay on `0.9.2` for any reason or if we can upgrade this for all. If any have to stay …
=> Use Thrift 0.13.0

.gitignore, Makefile, proto/api_v2/model.proto, thrift/agent.thrift, thrift/aggregation_validator.thrift, thrift/baggage.thrift, thrift/crossdock/tracetest.thrift, thrift/dependency.thrift, thrift/jaeger.thrift, thrift/sampling.thrift, thrift/throttling.thrift, thrift/zipkincore.thrift
- Fixes #62 
- Blocked by https://github.com/jaegertracing/docker-protobuf/pull/15
* Thrift doesn't support netcore in 0.13.0 anymore
* C# can't be generated with 0.9.2, but 0.13.0 can't be used as blocked by https://github.com/ahawkins/docker-thrift/pull/22
* Therefore only preparations made
* Removed unused import in model.proto to avoid warnings
* Improved Makefile to make it easier to read and maintain
* Generate annotation protos necessary in C# for reflection
=> Improve csharp support

proto/api_v3/query_service.proto, proto/api_v3/query_service_http.yaml
Signed-off-by: Pavol Loffay <p.loffay@gmail.com>
Related to https://github.com/jaegertracing/jaeger/issues/169#issuecomment-856625509
=> Add gRPC query service with OTLP model

proto/api_v3/query_service_http.yaml
This is a bug fix, without this the compilation for grp-gateway does not work
=> Fix selector for grpc gateway in apiv3

proto/api_v3/query_service.proto
Example query: 
```
curl -H "Content-Type: application/json" http://localhost:16686/v3/traces\?query.serviceName\=jaeger-query\&query.start_time_min\="2021-07-01T01:00:00Z"\&query.start_time_max\=2021-07-03T01:00:00Z\&query.duration_min\=0\&query.duration_max\=10s\&query.num_traces\=150000
```
Documenting this as it took me a while to realize which parameters are required and what is the format.
=> Document required fields in api_v3

proto/api_v3/query_service_http.yaml, swagger/api_v3/query_service.swagger.json
Signed-off-by: Pavol Loffay <p.loffay@gmail.com>
This aligns better with the current REST API e.g. `/api/service`.
cc) @vprithvi can we get this in before the release?
=> Add v3 prefix for v3

swagger/api_v3/query_service.swagger.json
Signed-off-by: Albert Teoh <see.kwang.teoh@gmail.com>
- Resolves #90
- Bumps the version of the opentelemetry-proto submodule to the latest [v0.13.0 tag](https://github.com/open-telemetry/opentelemetry-proto/releases/tag/v0.13.0) to fix the broken builds.
This change is the result of the following commands:
```
make init-submodule
cd opentelemetry-proto
git ls-remote --tags origin
git fetch
git checkout v0.13.0
make proto
```
=> Update otel proto to latest tag v0.13.0

proto/api_v2/query.proto, proto/api_v3/query_service.proto, swagger/api_v3/query_service.swagger.json
- https://github.com/jaegertracing/jaeger/issues/4150
- allow optional time parameters when querying trace by id
=> Add start and end timestamp args to GetTrace request

proto/api_v2/query.proto, proto/api_v3/query_service.proto
- The new timestamp fields added in #95 did not have the gogo mappings to use stdlib's time.Time 
- add gogo annotations
- CI
=> Add Go type mapping for new timestamp fields from #95

Makefile, proto/api_v3/query_service.proto
- When adding tests for APIv3 using grpc-gateway (https://github.com/jaegertracing/jaeger/pull/5051), I discovered that it returns additional types beyond what's declared in the IDL (specifically error struct and a wrapper for chunked responses).
- Add helper types to IDL so that callers can use them to parse the responses
- Bump protoc Docker image version to v.0.5.0 already used by the main repo
- Tested in the upcoming PR in the jaeger repo
=> Add grpc-gateway helper types

proto/api_v3/query_service.proto
- See https://github.com/jaegertracing/jaeger/pull/5098
- Replace `SpansResponseChunk` with `opentelemetry.proto.trace.v1.TracesData`
- In https://github.com/jaegertracing/jaeger/pull/5098
=> Replace api_v3.SpansResponseChunk with opentelemetry.proto.trace.v1.TracesData

Makefile, swagger/zipkin2-api.yaml
- Swagger Docker image is no longer value
- Upgrade swagger image version to 0.31
- That fails on the old API definition for Zipkin, so update that from the latest
- CI
=> Update Zipkin API

proto/api_v3/query_service.proto, swagger/api_v3/query_service.swagger.json
- Part of https://github.com/jaegertracing/jaeger/issues/4150
- Having gogo annotations in the IDL makes it difficult to users to build clients
- Remove gogo annotations
- Rename num_traces to search_depth
- Tested in https://github.com/jaegertracing/jaeger/pull/6233
=> Remove gogo annotations

proto/api_v2/query.proto
Part of https://github.com/jaegertracing/jaeger/issues/4150
- Make sure type of time fields are aligned with other requests
- unit test
- for `jaeger`: `make lint test`
- for `jaeger-ui`: `yarn lint` and `yarn test`
=> [api_v2] Change time fields in ArchiveTraceRequest to non-nullable for gogo

proto/api_v2/query.proto, proto/api_v3/query_service.proto, swagger/api_v3/query_service.swagger.json
- Towards https://github.com/jaegertracing/jaeger/issues/6417
- Added the `raw_traces` parameter to the `GetTraceRequest` and the `TraceQueryParameters` in the `FindTracesRequest`
- for `jaeger`: `make lint test`
- for `jaeger-ui`: `npm run lint` and `npm run test`
=> [query][api_v2/v_3] Add raw_traces parameter to GetTraceRequest and FindTracesRequest

model/v1/dependencies.go, model/v1/dependencies_test.go, model/v1/hash.go, model/v1/hash_test.go, model/v1/ids.go, model/v1/keyvalue.go, model/v1/keyvalue_test.go, model/v1/keyvalues_test.go, model/v1/process.go, model/v1/process_test.go
[#6571](https://github.com/jaegertracing/jaeger/issues/6571)
- Copy set of types from original `model/` -> `dependencies.go`, `hash.go`, `keyvalue.go`, `process.go` 
- `go test ./model/v1`
- for lint: `golangci-lint run  ./model/v1/`
- for tests: `go test ./model/v1`
=> add models for dependencies.go, hash.go, keyvalue.go, process.go

Makefile
when running `make proto` a warning was logged
```
model/proto: warning: directory does not exist.
```
- Remove unused import path
=> Remove -Imodel/proto

.gitignore, Makefile, README.md
=> Compile thrift into dot-dir .thrift-gen-polyglot

.github/workflows/ci-lint-test.yml, go.mod
- Resolves https://github.com/jaegertracing/jaeger/issues/6734
- Successor of #144 
- 
- 
- for `jaeger`: `make lint test`
- for `jaeger-ui`: `npm run lint` and `npm run test`
=> Upgrade Go version to 1.24

Makefile, proto/storage/v2/dependency_storage.proto, proto/storage/v2/trace_storage.proto
- Towards https://github.com/jaegertracing/jaeger/issues/7089
- This PR copies the gRPC API definitions from `jaeger` to this repository. In a follow-up PR, the proto definitions will be removed from `jaeger` and will point to this repo instead.
- CI
- for `jaeger`: `make lint test`
- for `jaeger-ui`: `npm run lint` and `npm run test`
=> [grpc][v2] Move gRPC API from `jaeger` to `jaeger-idl`
